name: My First Workflow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install cowsay
              run: sudo apt-get install cowsay
            - name: Say hello
              run: 
                cowsay "Hello Linux"
                ls -ltra
                cat README.md
