name: My Second Workflow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install cowsay
              run: sudo apt-get install cowsay
            - name: Execute Shell Script
              run: 
                ./ascii-script.sh
