
name: Exploring variable and secrets
on:
    push 
env:
    CONTAINER_REGISTRY: docker.io
    DOCKER_USERNAME: namnlp
    IMAGE_NAME: nginx
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
        - name: Docker Build
          run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
        - name: Docker Login
          env: 
            DOCKER_PASSWORD: P@ssword123
          run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
