name: My Third Workflow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Build Job
              uses: actions/checkout@v4

            - name: Install cowsay
              run: sudo apt-get install cowsay
            - name: Cowsay
              run: cowsay hello > hello.txt
    second_job:
        needs: first_job
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/upload-artifact@v4
              with:
                name: my-artifact
                path: cowsayhello.txt
    third_job:
        needs: second_job
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/download-artifact@v4
              with:
                name: my-artifact
                path: cowsayhello.txt

        
        
